favicon: /favicon.ico


# Nav Menus
menu:
    Home: /
    Archives: /archives
    Categories: /categories
    Tags: /tags

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/mirsery']
    - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    - ['github', 'https://github.com/mirsery', 'https://github.com/mirsery']
    - ['weibo', 'https://weibo.com/lengyekuyu', 'https://weibo.com/lengyekuyu']


# About
about_info:
    name: "mirsery"
    bio: "Have a nice day."
    avatar: "/images/avatar.png"

# Comment
# e.g disqus: seansun
disqus: mirsery
duoshuo:

# Analytics
google_analytics: mirsery
tencent_analytics: 
 
# Copyright Infomation
startyear: 2015