favicon: /favicon.ico

# Nav Menus
menu:
    Home: /
    Archives: /archives
    Categories: /categories
    Tags: /tags

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/mirsery']
    - ['/images/rss.svg', '/atom.xml']
    - ['/images/zhihu.svg','https://www.zhihu.com/people/mirsery']

# Friend Links
friend_links:
    - ['BlitheZhu','小朱的博客','https://blitheZhu.github.io']
    - ['happyafa','阿发的博客','https://happyafa.github.io']


# About
about_info:
    name: "mirsery"
    bio: 'Be you wanna be...'
    avatar: "/images/avatar.png"

# Comment
# e.g disqus: seansun
disqus: mirsery
duoshuo:

# Analytics
google_analytics: mirsery
tencent_analytics: 
 
# Copyright Infomation
startyear: 2015

feed:
  limit: 20
  order_by: -date
  icon: "/images/avatar.png"